- name: Configure Git credentials
  run: |
    git config --global user.name "GitHub Bot"
    git config --global user.email "bot@example.com"
    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

- name: Make a dummy commit
  run: |
    date > last-updated.txt
    git add .
    git commit -m "New commit: $(date)" || echo "No changes to commit"
    git push
